language: java

sudo: false

before_install:
  - chmod +x mvnw

script: ./mvnw clean package -Dmaven.javadoc.skip=true

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - juraj.somorovsky@hackmanit.de
