language: java

sudo: false

script: ./mvnw clean package

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - juraj.somorovsky@hackmanit.de