language: java

sudo: false

before_install:
  - chmod +x mvnw

script: ./mvnw -Ptravis clean package

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - juraj.somorovsky@hackmanit.de
